name: Create pull request from staging to master
on:
  push:
    branches:
      - staging
jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: pull-request
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_title: "Release"
          pr_label: "production-release"
          destination_branch: "master"

